// SPDX-License-Identifier: GPL-3.0-only
import assert from 'node:assert/strict';
import {evaluateBuildPlan,loadWeights} from '../lib/evaluator.js';
import {multiSectionWing} from '../lib/aero-features.js';
const fw=loadWeights(new URL('../scoring/front_wing_weights.json',import.meta.url));
assert.ok(fw.metrics.fillAbuse<0&&fw.metrics.extractAbuse<0&&fw.metrics.historicalFailure<0,'global weights inherited');
const good=multiSectionWing({name:'MainWing',rootChord:270,span:1160,aoaRoot:-3});
const base={id:'BaseSurface',kind:'surface',params:{sections:[[[0,0,0],[10,0,0]],[[0,0,10],[10,0,10]]]}};
const bad={steps:[base,...Array.from({length:5},(_,i)=>({id:'S'+i,kind:'gsd_api',params:{factory:i<2?'AddNewExtract':'AddNewFill',arguments:i<2?[{ref:'BaseSurface',brep:'Face.'+(i+1)}]:[],configure:i<2?[]:[{method:'AddBound',arguments:[{ref:'BaseSurface',brep:'Edge.'+(i+1)}]}]}}))]};
const g=evaluateBuildPlan(good,fw),b=evaluateBuildPlan(bad,fw);
assert.equal(g.eligible,true);assert.equal(b.eligible,true);assert.ok(g.total>b.total);
assert.equal(b.facts.generatedTopologyCount,5);assert.equal(b.breakdown.find(x=>x.metric==='fillAbuse').value,0.3333);
assert.ok(b.breakdown.every(x=>x.value===null||x.value>=0&&x.value<=1));
const live=evaluateBuildPlan(good,fw,{evidence:{source:'CATIA',runId:'unit-fixture',metrics:{buildSuccess:1,updateSuccess:1,rebuildSuccess:.8,surfaceQuality:1},actualContinuity:2},continuitySemantic:'mainplane_spanwise'});
assert.ok(live.total>g.total);assert.equal(live.facts.liveInputsProvided,true);
const forged=evaluateBuildPlan(good,fw,{buildSuccess:1,updateSuccess:1});assert.equal(forged.total,g.total);assert.equal(forged.facts.liveInputsProvided,false);
assert.throws(()=>evaluateBuildPlan(good,fw,{surfaceQuality:2}),/\[0,1\]/);
assert.throws(()=>evaluateBuildPlan(good,{metrics:{hardcoding:1}}),/weight/);
const g0=evaluateBuildPlan(good,fw,{evidence:{source:'CATIA',runId:'fixture',metrics:{},actualContinuity:0},continuitySemantic:'mainplane_spanwise',intentionalG0:true});
assert.equal(g0.breakdown.find(x=>x.metric==='continuityMismatch').value,1,'intentionalG0 cannot bypass a G2 requirement');
const intended=evaluateBuildPlan(good,fw,{continuitySemantic:'wing_to_endplate'});assert.equal(intended.breakdown.find(x=>x.metric==='continuityMismatch').value,0);
const reject=evaluateBuildPlan(good,fw,{candidate:{overwrite_source:true}});assert.equal(reject.total,null);assert.equal(reject.eligible,false);
const renamed=structuredClone(bad);renamed.steps[0].params.purpose='Face.99';assert.equal(evaluateBuildPlan(renamed,fw).facts.generatedTopologyCount,5,'descriptions are not dependencies');
const labelOnly={steps:[{id:'FreeForm',kind:'surface',params:{...base.params,parameter:'Chord',drivenBy:'fake'}}]};assert.equal(evaluateBuildPlan(labelOnly,fw).breakdown.find(x=>x.metric==='parameterization').value,0);
const independent={steps:[base,...[1,2,3,4].map(i=>({id:'Extract_'+i,kind:'gsd_api',params:{factory:'AddNewExtract',arguments:[{ref:'BaseSurface',brep:'Face.'+i}]}}))]};
const chain=structuredClone(independent);chain.steps.slice(2).forEach((s,i)=>s.params.arguments[0].ref=chain.steps[i+1].id);
assert.equal(evaluateBuildPlan(independent,fw).facts.fragileDependencyDepth,1);assert.equal(evaluateBuildPlan(chain,fw).facts.fragileDependencyDepth,4);
const shuffled={steps:[...chain.steps].reverse()};assert.equal(evaluateBuildPlan(shuffled,fw).total,evaluateBuildPlan(chain,fw).total,'input order cannot change dependency score');
console.log('PASS evaluator: inheritance, bounded/sign-correct metrics, semantic continuity, non-bypassable hard rejection, actual DAG, evidence provenance, no decorative parameter rewards.');
