// SPDX-License-Identifier: GPL-3.0-only
/** Synthetic evidence only; never attaches to CATIA or installs resources. */
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {evaluateBuildPlan,loadWeights} from '../lib/evaluator.js';
import {planningAdvice,planningHabits,closurePolicy,buildFingerprint,repairEvidenceFromAudit} from '../lib/planning-policy.js';
import {buildToolDefinitions} from '../lib/tools.js';
import {buildPersona} from '../lib/prompt.js';
import {elementFragment} from '../lib/ops.js';
import {apiElement} from '../lib/gsd-api.js';
const weights=loadWeights(new URL('../scoring/front_wing_weights.json',import.meta.url));
let checks=0,calls=0;const check=f=>{f();checks++;};
const curve={id:'Outline',kind:'guide_curve',task:'planar_closed_profile',params:{points:[[0,0,0],[100,0,0],[100,50,0],[0,50,0]],closed:false}};
const edge={id:'ClosingEdge',kind:'line',params:{x1:0,y1:50,z1:0,x2:0,y2:0,z2:0}};
const join={id:'RepairJoin',kind:'gsd_api',task:'closure_repair',params:{factory:'AddNewJoin',arguments:[{ref:'Outline'},{ref:'ClosingEdge'}]}};
const requirement={target:'Outline',type:'closed_wire',reason:'Material perimeter must close'};
const open={steps:[curve,edge,join],geometryRequirements:[requirement]};
const baseline=evaluateBuildPlan(open,weights);
check(()=>assert.equal(baseline.eligible,true));
check(()=>assert.equal(baseline.closure.openCount,1));
check(()=>assert.equal(baseline.readyForDelivery,false));
check(()=>assert.equal(baseline.closurePenaltyPoints,6));
check(()=>assert.equal(baseline.status,'PARTIAL_SUCCESS'));
check(()=>assert.ok(baseline.toolAdvice.some(f=>f.code==='sketch-first')));
check(()=>assert.ok(baseline.breakdown.find(m=>m.metric==='toolMisuse').value>0));
const attempt={attemptId:'SyntheticAttempt',target:'Outline',type:'closed_wire',stepId:'RepairJoin',executed:true,outcome:'failed'};
const ev={source:'CATIA',runId:'synthetic-not-live',repairAttempts:[attempt]};
const repaired=evaluateBuildPlan(open,weights,{evidence:ev});
check(()=>assert.equal(repaired.closurePenaltyPoints,4.5));
check(()=>assert.equal(repaired.readyForDelivery,false));
check(()=>assert.equal(repaired.score100-baseline.score100,1.5));
check(()=>assert.equal(evaluateBuildPlan(open,weights,{evidence:{...ev,repairAttempts:Array(20).fill(attempt)}}).closurePenaltyPoints,4.5));
for(const evidence of [{...ev,source:'LLM'},{...ev,runId:''},{...ev,repairAttempts:[{...attempt,executed:false}]},{...ev,repairAttempts:[{...attempt,stepId:'ClosingEdge'}]},{...ev,repairAttempts:[{...attempt,target:'Fake'}]},{...ev,repairAttempts:[{...attempt,type:'solid'}]}]) check(()=>assert.equal(evaluateBuildPlan(open,weights,{evidence}).closurePenaltyPoints,6));
check(()=>assert.equal(evaluateBuildPlan(open,weights,{candidate:{overwrite_source:true},evidence:ev}).score100,null));
check(()=>assert.equal(evaluateBuildPlan({...open,steps:[{...curve,params:{...curve.params,closed:'false'}},edge,join]},weights).eligible,false));
const sketch={id:'Outline',kind:'sketch',task:'planar_closed_profile',params:{plane:'XY',points:[[0,0],[100,0],[100,50],[0,50]],constraints:[{type:'length',edge:0,value:100}]}};
const body={id:'Wall',kind:'capped_extrude',task:'solid',part:'Endplate',params:{from:'Outline',direction:[0,0,1],length:2}};
const sketchPlan={steps:[sketch,body],geometryRequirements:[requirement,{target:'Wall',type:'solid',reason:'Final material solid'}]};
check(()=>assert.equal(evaluateBuildPlan(sketchPlan,weights).eligible,true));
check(()=>assert.equal(planningHabits(sketchPlan.steps).habitMeaningfulConstraints,1));
check(()=>assert.equal(planningHabits([sketch]).habitMeaningfulConstraints,null));
check(()=>assert.equal(evaluateBuildPlan(sketchPlan,weights).closurePenaltyPoints,1));
check(()=>assert.equal(evaluateBuildPlan(sketchPlan,weights).readyForDelivery,false));
check(()=>assert.equal(closurePolicy(sketchPlan).findings[0].state,'CLOSED_INPUT'));
const unconstrained=structuredClone(sketchPlan);delete unconstrained.steps[0].params.constraints;
check(()=>assert.equal(planningHabits(unconstrained.steps).habitMeaningfulConstraints,0));
check(()=>assert.ok(planningAdvice(unconstrained.steps).some(f=>f.code==='try-dimensional-constraints')));
check(()=>assert.ok(evaluateBuildPlan(sketchPlan,weights).score100>=evaluateBuildPlan(unconstrained,weights).score100));
const badLength=structuredClone(sketchPlan);badLength.steps[0].params.constraints[0].value=99;
check(()=>assert.equal(evaluateBuildPlan(badLength,weights).eligible,false));
const inspected={updated:true,measurementId:'synthetic-inspection',closed:true,boundaryCount:0,manifold:true,oriented:true,connectedComponents:1,volumeMm3:10000,bodyCount:1};
const native={source:'CATIA',runId:'synthetic-not-live',closure:{Outline:{closed_wire:inspected},Wall:{solid:inspected}}};
check(()=>assert.equal(closurePolicy(sketchPlan,weights,{evidence:native}).readyForDelivery,true));
for(const patch of [{bodyCount:2},{connectedComponents:2},{manifold:false},{boundaryCount:1},{volumeMm3:0},{updated:false},{measurementId:''}]) {
 const e=structuredClone(native);e.closure.Wall.solid={...inspected,...patch};
 check(()=>assert.equal(closurePolicy(sketchPlan,weights,{evidence:e}).readyForDelivery,false));
}
check(()=>assert.equal(closurePolicy({...sketchPlan,geometryRequirements:[]}).readyForDelivery,false));
const noRequirements={steps:[curve]};check(()=>assert.equal(closurePolicy(noRequirements).readyForDelivery,false));
for(const reqs of [[{...requirement,target:'Missing'}],[{...requirement,type:'watertight'}],[{...requirement,reason:''}],[requirement,requirement]]) check(()=>assert.equal(evaluateBuildPlan({...open,geometryRequirements:reqs},weights).eligible,false));
const sheet={id:'Sheet',kind:'surface',params:{sections:[[[0,0,0],[10,0,0],[10,5,0]],[[0,0,2],[10,0,2],[10,5,2]]],closed:true}};
const shellPlan={steps:[sheet],geometryRequirements:[{target:'Sheet',type:'closed_shell',reason:'Needs caps'}]};
check(()=>assert.equal(closurePolicy(shellPlan).openCount,1));
check(()=>assert.equal(closurePolicy({steps:[sketch],geometryRequirements:[{target:'Outline',type:'solid',reason:'A sketch is not a solid'}]},weights,{evidence:{source:'CATIA',runId:'synthetic',closure:{Outline:{solid:inspected}}}}).openCount,1));
check(()=>assert.equal(buildFingerprint(open.steps),buildFingerprint([...open.steps].reverse())));
const record={buildFingerprint:buildFingerprint(open.steps),runId:'synthetic-host-run',status:'failed',result:{attempted_RepairJoin:'AddNewJoin'}};
check(()=>assert.equal(evaluateBuildPlan(open,weights,{evidence:repairEvidenceFromAudit(open,[record])}).closurePenaltyPoints,4.5));
check(()=>assert.equal(repairEvidenceFromAudit(open,[{...record,buildFingerprint:'stale'}]),undefined));
check(()=>assert.equal(repairEvidenceFromAudit(open,[{...record,status:'blocked'}]),undefined));
check(()=>assert.equal(evaluateBuildPlan(open,weights,{evidence:repairEvidenceFromAudit(open,[{...record,result:{}}])}).closurePenaltyPoints,6));
const marker=apiElement(join),markerAt=marker.indexOf('Emit "attempted_RepairJoin"');
check(()=>assert.ok(markerAt>=0&&markerAt<marker.indexOf('Set feat = gHsf.AddNewJoin')));
check(()=>assert.ok(elementFragment(sketch).includes('MakeSketch')));
const defs=buildToolDefinitions({readLedger:()=>null,readAudit:()=>[record],run:async()=>{calls++;throw Error('must stay offline');}}, {maxLevel:2,persona:true});
const evaluate=defs.find(t=>t.name==='catia_evaluate_plan');
check(()=>assert.ok(!Object.hasOwn(evaluate.parameters.properties,'evidence')));
const offline=await evaluate.execute({...open,component:'front_wing'}),withAudit=await evaluate.execute({...open,component:'front_wing',project:'SYNTHETIC'});
check(()=>assert.equal(offline.evaluation.closurePenaltyPoints,6));
check(()=>assert.equal(withAudit.evaluation.closurePenaltyPoints,4.5));
check(()=>assert.equal(offline.status,'PARTIAL_SUCCESS'));
const dry=await defs.find(t=>t.name==='catia_model_plan').execute({...sketchPlan,project:'SYNTHETIC',dryRun:true});
check(()=>assert.equal(dry.status,'SUCCESS'));
check(()=>assert.equal(dry.closure.readyForDelivery,false));
const status=await defs.find(t=>t.name==='catia_policy_status').execute({});
check(()=>assert.equal(status.deployment.registration.revision,'r11'));
check(()=>assert.equal(status.deployment.registration.gsd.factories,145));
check(()=>assert.equal(status.deployment.registration.resources.length,26));
check(()=>assert.ok(defs.find(t=>t.name==='catia_policy_status').output.render({},status)[0].text.includes('r11')));
const persona=buildPersona({maxLevel:2});
check(()=>assert.ok(persona.includes('r11')&&persona.includes('geometryRequirements')&&persona.includes('catia_policy_status')));
check(()=>assert.ok(!/Sketcher 尚未实现|Sketcher、Pad\/Pocket\/通用 Boolean 等未实现/.test(persona)));
for(const file of ['front_wing_design.md','global_aero_design.md']) check(()=>assert.ok(readFileSync(new URL('../skills/'+file,import.meta.url),'utf8').includes('r11')));
const rules=JSON.parse(readFileSync(new URL('../rules/fsec_rules.json',import.meta.url),'utf8'));
check(()=>assert.equal(rules.rules.find(r=>r.rule_id==='T9.6-250MM-ZONE').parameter,'max_height_ahead_front_axle_outside_tire_inner'));
check(()=>assert.ok(rules.rules.filter(r=>r.source_type==='competition').every(r=>r.verification_status==='UNVERIFIED')));
check(()=>assert.equal(closurePolicy({steps:open.steps}).openCount,1,'closed task infers closure even without an explicit declaration'));
check(()=>assert.equal(buildFingerprint([{id:'Solid',kind:'gsd',params:{op:'solid_close',from:'Shell'}}]),buildFingerprint([{id:'Solid',kind:'gsd',params:{op:'solid_close',from:['Shell']}}])));
const unionScript=apiElement({id:'NextUnion',params:{factory:'AddNewAdd',arguments:[{ref:'Independent'}],bodySource:'PreviousUnion'}});
check(()=>assert.ok(unionScript.includes('gFeats.Exists("PreviousUnion__body")')&&unionScript.includes('gPart.InWorkObject = targetBody')));
check(()=>assert.equal(calls,0));
for(const setting of [{closurePenaltyCapPoints:3},{closureRepairMitigation:.5},{closureUnknownPenaltyPoints:3}]) check(()=>assert.throws(()=>evaluateBuildPlan(open,{...weights,...setting}),/allowed range/));
console.log(`PASS r10: ${checks} checks for routing, useful constraints, closure obligations, bounded repair relief, journal fingerprints, unchanged hard rejections, deployment freshness and offline tool integration. Evidence fixtures are synthetic.`);
