// SPDX-License-Identifier: GPL-3.0-only
/** Offline synthetic plans and bridge stubs only. */
import assert from 'node:assert/strict';
import {preparePlan,routeAudit} from '../lib/plan-routing.js';
import {elementFragment,elementGeometry,orderedElements} from '../lib/ops.js';
import {sketchInput} from '../lib/sketch-input.js';
import {closurePolicy,buildFingerprint,planningHabits} from '../lib/planning-policy.js';
import {validateOperationSources} from '../lib/operation-contract.js';
import {buildToolDefinitions} from '../lib/tools.js';
import {evaluateBuildPlan,loadWeights} from '../lib/evaluator.js';
import {PRELUDE} from '../lib/vbs.js';
let checks=0,calls=0;const check=f=>{f();checks++;};
const patch={id:'Foot',kind:'surface',part:'Endplate',params:{sections:[[[10,20,30],[110,20,30]],[[10,20,50],[110,20,50]]],closed:false}};
const original=JSON.stringify(patch),prepared=preparePlan([patch]);
check(()=>assert.equal(JSON.stringify(patch),original));
check(()=>assert.equal(prepared.changes.length,1));
check(()=>assert.equal(prepared.steps.length,3));
check(()=>assert.equal(prepared.steps.at(-1).id,'Foot'));
check(()=>assert.equal(prepared.steps.at(-1).kind,'gsd'));
check(()=>assert.equal(prepared.routeAudit.consumedSketchCount,2));
check(()=>assert.equal(prepared.routeAudit.requestedConstraintCount,4));
check(()=>assert.deepEqual(prepared.routeAudit.sampledCurveIds,[]));
for(let i=0;i<2;i++)check(()=>assert.deepEqual(sketchInput(prepared.steps[i].params).world,patch.params.sections[i]));
check(()=>assert.deepEqual(preparePlan(prepared.steps).steps,prepared.steps));
const map=Object.fromEntries(prepared.steps.map(s=>[s.id,s]));
check(()=>assert.deepEqual(orderedElements(map).map(s=>s.id),prepared.steps.map(s=>s.id)));
check(()=>prepared.steps.forEach(s=>validateOperationSources(s,map)));
check(()=>assert.equal(planningHabits(prepared.steps).habitMeaningfulConstraints,1));
check(()=>assert.notEqual(buildFingerprint([patch]),buildFingerprint(prepared.steps)));
check(()=>assert.ok(!elementFragment(patch).includes('MakeSpline')));
check(()=>assert.ok(elementFragment(patch).includes('MakeLine')));
const lineGuide={id:'Guide',kind:'guide_curve',params:{points:[[0,0,0],[10,20,30]],closed:false}};
check(()=>assert.ok(elementFragment(lineGuide).includes('MakeLine')));
const free={id:'Curved',kind:'guide_curve',params:{points:[[0,0,0],[10,5,0],[20,0,0]],closed:false}};
check(()=>assert.deepEqual(preparePlan([free]).steps,[free]));
check(()=>assert.ok(elementFragment(free).includes('MakeSpline')));
const dense={id:'Dense',kind:'surface',params:{sections:[[[0,0,0],[10,5,0],[20,0,0]],[[0,0,10],[10,5,10],[20,0,10]]],closed:false}};
check(()=>assert.deepEqual(preparePlan([dense]).steps,[dense]));
check(()=>assert.throws(()=>preparePlan([patch],{routeMode:'literal'}),/routeReason/));
check(()=>assert.deepEqual(preparePlan([patch],{routeMode:'literal',routeReason:'Compare old native line route'}).steps,[patch]));
check(()=>assert.throws(()=>preparePlan([patch,{id:'Foot__sketch_1',kind:'point',params:{x:0,y:0,z:0}}]),/collision/));
const open={id:'Open',kind:'sketch',params:{points:[[0,0],[100,0]],closed:false,constraints:[{type:'length',edge:0,value:100},{type:'horizontal',edge:0}]}};
check(()=>assert.equal(sketchInput(open.params).edgeCount,1));
check(()=>assert.ok(elementFragment(open).includes('False')));
check(()=>assert.equal(closurePolicy({steps:[open],geometryRequirements:[{target:'Open',type:'closed_wire',reason:'Should close'}]}).openCount,1));
check(()=>assert.throws(()=>validateOperationSources({id:'Body',kind:'capped_extrude',params:{from:'Open',length:2,direction:[0,0,1]}},{Open:open}),/closed sketch/));
check(()=>assert.throws(()=>validateOperationSources({id:'Fill',kind:'gsd',params:{op:'fill',from:['Open']}},{Open:open}),/closed sketch/));
const points=[[0,0],[100,0],[100,50],[0,50]];
for(const c of [{type:'horizontal',edge:0},{type:'vertical',edge:1},{type:'parallel',edge:0,otherEdge:2},{type:'perpendicular',edge:0,otherEdge:1}])check(()=>assert.equal(sketchInput({points,constraints:[c]}).constraints[0].type,c.type));
for(const c of [{type:'horizontal',edge:1},{type:'vertical',edge:0},{type:'parallel',edge:0,otherEdge:1},{type:'perpendicular',edge:0,otherEdge:2},{type:'parallel',edge:0,otherEdge:0},{type:'horizontal',edge:0,value:1},{type:'radius',edge:0,value:3},{type:'length',edge:0,value:99},{type:'length',edge:0,otherEdge:1,value:100}])check(()=>assert.throws(()=>sketchInput({points,constraints:[c]})));
check(()=>assert.throws(()=>sketchInput({points,closed:'false'})));
check(()=>assert.throws(()=>sketchInput({points:[[0,0],[1,0],[0,0]],closed:false})));
check(()=>assert.throws(()=>sketchInput({points,constraints:[{type:'horizontal',edge:0},{type:'horizontal',edge:0}]})));
check(()=>assert.ok(PRELUDE.includes('sk.Constraints.AddBiEltCst(2, refLine, refOther)')));
check(()=>assert.ok(PRELUDE.includes('sketchConstraintStatuses_')));
check(()=>assert.ok(PRELUDE.includes('sketch solver moved a profile edge; bounds invalid')));
check(()=>assert.ok(!PRELUDE.includes('closure from explicit coordinates')));
const defs=buildToolDefinitions({readLedger:()=>null,run:async()=>{calls++;throw Error('must stay offline');}},{maxLevel:2});
check(()=>assert.equal(defs.length,44));
const prepare=defs.find(d=>d.name==='catia_prepare_plan'),plan=defs.find(d=>d.name==='catia_model_plan'),sketch=defs.find(d=>d.name==='catia_sketch');
const out=await prepare.execute({steps:[patch]});
check(()=>assert.equal(out.status,'SUCCESS'));
check(()=>assert.equal(out.routeAudit.consumedSketchCount,2));
const dry=await plan.execute({project:'Synthetic',steps:[patch],dryRun:true});
check(()=>assert.equal(dry.status,'SUCCESS'));
check(()=>assert.equal(dry.routing.changes.length,1));
check(()=>assert.equal(dry.routeAudit.requestedConstraintCount,4));
check(()=>assert.equal(dry.preparedSteps.length,3));
const literal=await plan.execute({project:'Synthetic',steps:[patch],dryRun:true,routeMode:'literal'});
check(()=>assert.equal(literal.status,'BLOCKED'));
const sd=await sketch.execute({project:'Synthetic',id:'Open',...open.params,dryRun:true});
check(()=>assert.equal(sd.status,'SUCCESS'));
check(()=>assert.equal(sd.routeAudit.sketches[0].closed,false));
const bad=await sketch.execute({project:'Synthetic',id:'Open',...open.params,dryRun:'true'});
check(()=>assert.equal(bad.status,'BLOCKED'));
check(()=>assert.equal(calls,0));
for(const id of ['__proto__','constructor','prototype','bad/path','bad\\path']) {
  const unsafe=await prepare.execute({steps:[{...patch,id}]});
  check(()=>assert.equal(unsafe.status,'BLOCKED'));
}
const empty=await prepare.execute({steps:[]});
check(()=>assert.equal(empty.status,'BLOCKED'));
check(()=>assert.equal(sketch.parameters.properties.constraints.items.properties.edge.type,'number'));
check(()=>assert.ok(PRELUDE.includes('If cStatus <> 0 Then')));
check(()=>assert.ok(PRELUDE.includes('sketch constraint inactive')));
check(()=>assert.ok(PRELUDE.includes('sketchConstraintsSatisfied_')));
check(()=>assert.throws(()=>elementFragment({id:'Zero',kind:'guide_curve',params:{points:[[0,0,0],[0,0,0]]}}),/distinct endpoints/));
check(()=>assert.throws(()=>preparePlan([{...patch,id:'X'.repeat(96)}]),/96 characters/));
const tooMany=await prepare.execute({steps:Array(2049).fill(patch)});
check(()=>assert.equal(tooMany.status,'BLOCKED'));
const evaluation=evaluateBuildPlan({steps:prepared.steps},loadWeights(new URL('../scoring/front_wing_weights.json',import.meta.url)));
check(()=>assert.equal(evaluation.eligible,true));
check(()=>assert.equal(evaluation.readyForDelivery,false));
check(()=>assert.equal(elementGeometry(prepared.steps[0]).boundsCertified,true));
console.log(`PASS r11: ${checks} offline checks for exact routing, consumption, constraints, open/closed contracts, no fabricated endpoint verification and tool integration. No CATIA execution.`);
