// SPDX-License-Identifier: GPL-3.0-only
/** Regression checks for filled plates, batch topology, fail-closed completion and portable delivery. */
import assert from 'node:assert/strict';
import { mkdtempSync,rmSync,existsSync,readFileSync,writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { CatiaBridge,normalizeSettings } from '../lib/bridge.js';
import { buildToolDefinitions } from '../lib/tools.js';
import { elementFragment,orderedElements,surfaceContours,elementGeometry,expectedGeometry } from '../lib/ops.js';
import { PRELUDE } from '../lib/vbs.js';
import { buildPersona } from '../lib/prompt.js';
let checks=0;
const check=fn=>{fn();checks++;};
const here=fileURLToPath(new URL('.',import.meta.url));
const temp=mkdtempSync(path.join(here,'r2-'));
try {
 const plate={id:'plate',kind:'endplate',params:{chord:300,height:120,thickness:2,z:0}};
 const script=elementFragment(plate);
 check(()=>assert.equal((script.match(/AddNewFill\(\)/g)||[]).length,2,'both broad plate faces must be filled'));
 check(()=>assert.ok(script.includes('MakePolygon')));
 check(()=>assert.ok(script.includes('AddNewExtrude')));
 check(()=>assert.ok(script.includes('AddNewJoin')));
 check(()=>assert.ok(!script.includes('MakeLoft "plate"')));
 check(()=>assert.ok(PRELUDE.includes('amount = meas.Area')));
 check(()=>assert.ok(PRELUDE.includes('amount = meas.Volume')));
 check(()=>assert.ok(PRELUDE.includes('verified_')));
 check(()=>assert.equal(expectedGeometry({kind:'gsd',params:{op:'solid_close'}}),'solid'));
 const params={sections:[[[0,0,0],[20,0,0]],[[0,10,3],[20,10,3]]]};
 check(()=>assert.equal(surfaceContours(params).length,2));
 check(()=>assert.equal(elementGeometry({id:'panel',kind:'surface',params}).boundsCertified,false));
 check(()=>assert.throws(()=>surfaceContours({sections:[params.sections[0],params.sections[0]]}),/coincide/));
 check(()=>assert.throws(()=>surfaceContours({sections:[[[0,0,0],[20,0,0]],[[30,0,0],[50,0,0]]]}),/collapse/));
 check(()=>assert.throws(()=>surfaceContours({sections:[params.sections[0],[[0,10,3],[10,10,3],[20,10,3]]]}),/equal/));
 check(()=>assert.throws(()=>surfaceContours({...params,closed:'false'}),/boolean/));
 const source={id:'source',kind:'surface',params};
 const offset={id:'offset',kind:'gsd',params:{op:'offset',from:'source',distance:2}};
 check(()=>assert.deepEqual(orderedElements({offset,source}).map(e=>e.id),['source','offset']));
 check(()=>assert.throws(()=>orderedElements({offset}),/missing GSD/));
 check(()=>assert.throws(()=>orderedElements({a:{id:'a',kind:'gsd',params:{op:'offset',from:'b'}},b:{id:'b',kind:'gsd',params:{op:'offset',from:'a'}}}),/cyclic/));
 const root=path.join(temp,'projects');
 const bridge=new CatiaBridge(normalizeSettings({projectRoot:root,maxLevel:2},root));
 let calls=0,body='';
 bridge.run=async req=>{
   calls++;body=req.body;
   if(req.op==='catia_api_probe')return {ok:true,values:{},errors:[],durationMs:1};
   const ledger=bridge.readLedger(req.project),values={geometryReady:'true'};
   for(const e of Object.values(ledger.elements)){values['feature_'+e.id]=e.id;values['verified_'+e.id]='true';}
   return {ok:true,values,errors:['save unavailable'],durationMs:1};
 };
 const definitions=buildToolDefinitions(bridge,bridge.settings);
 const plan=definitions.find(t=>t.name==='catia_model_plan');
 const steps=[{...offset,params:{op:'offset',from:['source'],distance:2}},source];
 const dry=await plan.execute({project:'plan',steps,dryRun:true});
 check(()=>assert.equal(dry.status,'SUCCESS'));
 check(()=>assert.equal(calls,0));
 check(()=>assert.ok(!existsSync(root),'dry run must not create a project directory'));
 const built=await plan.execute({project:'plan',steps});
 check(()=>assert.equal(built.status,'PARTIAL_SUCCESS',JSON.stringify(built)));
 check(()=>assert.equal(calls,1,'the whole plan must rebuild exactly once'));
 check(()=>assert.equal(bridge.readLedger('plan').versions.length,1));
 check(()=>assert.ok(body.indexOf('VerifyFeature "source"')<body.indexOf('VerifyFeature "offset"')));
 const reject=async(args,pattern)=>{const before=calls;const out=await plan.execute(args);check(()=>assert.equal(out.status,'BLOCKED'));check(()=>assert.match(out.errors.join(' '),pattern));check(()=>assert.equal(calls,before));};
 await reject({project:'duplicate',steps:[source,source]},/duplicate/);
 await reject({project:'missing',steps:[{...offset,params:{op:'offset',from:['absent'],distance:2}}]},/missing GSD/);
 await reject({project:'wrong',steps:[{id:'p',kind:'point',params:{x:0,y:0,z:0}},{id:'bad',kind:'gsd',params:{op:'solid_thick',from:['p']}}]},/surface source/);
 await reject({project:'collision',steps:[plate,{id:'plate__front',kind:'point',params:{x:0,y:0,z:0}}]},/collides/);
 await reject({project:'too_many',steps:Array(2049).fill(source)},/1\.\.2048/);
 const blank=await definitions.find(t=>t.name==='catia_api_probe').execute({project:'empty_probe'});
 check(()=>assert.equal(blank.status,'FAILED','an empty successful bridge reply is not a verified probe'));
 const probeBridge=new CatiaBridge(normalizeSettings({projectRoot:path.join(temp,'probe'),maxLevel:1},temp));
 const probeValues=Object.fromEntries(['join','fill','loft','offset','extrude','solid_thick','solid_close'].map(op=>['api_'+op,'verified']));
 probeBridge.run=async()=>({ok:true,values:probeValues,lists:{},errors:[]});
 const probeTool=buildToolDefinitions(probeBridge,probeBridge.settings).find(t=>t.name==='catia_api_probe');
 const notClosed=await probeTool.execute({project:'probe'});
 check(()=>assert.equal(notClosed.status,'PARTIAL_SUCCESS'));
 for(const op of ['join','fill','loft','offset','extrude','solid_thick','solid_close'])probeValues['probeClosed_'+op]='true';
 const closedProbe=await probeTool.execute({project:'probe'});
 check(()=>assert.equal(closedProbe.status,'SUCCESS'));
 const readOnly=new CatiaBridge(normalizeSettings({projectRoot:path.join(temp,'read_only'),maxLevel:0},temp));
 let envCalls=0;
 readOnly.run=async()=>{envCalls++;return {ok:true,values:{},lists:{},errors:[]};};
 const envReadonly=buildToolDefinitions(readOnly,readOnly.settings).find(t=>t.name==='catia_env');
 const refusedWrite=await envReadonly.execute({project:'env',checkWrite:true});
 check(()=>assert.equal(refusedWrite.status,'BLOCKED'));
 check(()=>assert.equal(envCalls,0));
 check(()=>assert.equal(existsSync(readOnly.root),false));
 const envBridge=new CatiaBridge(normalizeSettings({projectRoot:path.join(temp,'env'),maxLevel:1},temp));
 let envRequest;
 const victim=path.join(temp,'unrelated.txt');writeFileSync(victim,'keep me');
 envBridge.run=async req=>{envRequest=req;return {ok:true,values:{saved:victim},lists:{openDoc:[]},errors:[]};};
 const env=buildToolDefinitions(envBridge,envBridge.settings).find(t=>t.name==='catia_env');
 const envResult=await env.execute({project:'env',checkWrite:true});
 check(()=>assert.equal(envResult.level,1));
 check(()=>assert.ok(envRequest.body.includes('gDoc.Close')));
 check(()=>assert.equal(readFileSync(victim,'utf8'),'keep me','only the exact own probe path may be deleted'));
 const invalidEnv=await env.execute({project:'env',checkWrite:null});
 check(()=>assert.equal(invalidEnv.status,'BLOCKED'));
 await env.execute({project:'env'});
 check(()=>assert.equal(envRequest.level,0));
 const badBridge=new CatiaBridge(normalizeSettings({projectRoot:path.join(temp,'bad'),maxLevel:2},temp));
 badBridge.run=async()=>({ok:true,values:{feature_p:'p',saved:'pretend.CATPart',geometryReady:'true'},errors:[],durationMs:1});
 const bad=await buildToolDefinitions(badBridge,badBridge.settings).find(t=>t.name==='catia_point').execute({project:'p',id:'p',x:0,y:0,z:0});
 check(()=>assert.equal(bad.status,'FAILED','saved/feature markers without verification cannot establish success'));
 check(()=>assert.equal(badBridge.readLedger('p'),null,'failed first build must restore absent ledger'));
 const persona=buildPersona({maxLevel:2});
 check(()=>assert.ok(persona.includes('catia_model_plan')&&persona.includes('catia_surface')));
 const metadata=JSON.parse(readFileSync(new URL('../package.json',import.meta.url),'utf8'));
 check(()=>assert.equal(metadata.version,'1.2.0'));
 check(()=>assert.equal(metadata.catiaAeroRevision,'r11'));
 check(()=>assert.ok(readFileSync(new URL('../cordis.patch.yml',import.meta.url),'utf8').includes("projectRoot: ''")));
 console.log('PASS: '+checks+' r2 filled-surface, plan, topology, fail-closed completion and delivery checks.');
} finally {
 if(path.resolve(path.dirname(temp))!==path.resolve(here))throw new Error('Unexpected temporary directory');
 rmSync(temp,{recursive:true,force:true});
}
